// .vitepress/theme/components/ScrollReveal.vue
<template>
  <div ref="el" class="scroll-reveal" :style="{ transitionDelay: `${delay}ms` }">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'

const props = defineProps<{ delay?: number }>()

const el = ref<HTMLElement | null>(null)

onMounted(() => {
  const node = el.value
  if (!node) return
  const io = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          node.classList.add('visible')
          io.unobserve(node)
        }
      })
    },
    { threshold: 0.1 }
  )
  io.observe(node)
})
</script>

<style scoped>
.scroll-reveal {
  opacity: 0;
  transform: translateY(24px);
  transition: opacity 0.7s cubic-bezier(0.22, 1, 0.36, 1),
              transform 0.7s cubic-bezier(0.22, 1, 0.36, 1);
}
.scroll-reveal.visible {
  opacity: 1;
  transform: none;
}
@media (prefers-reduced-motion: reduce) {
  .scroll-reveal { opacity: 1; transform: none; transition: none; }
}
</style>

// src/components/ScrollReveal.tsx
import React, { useEffect, useRef } from 'react'

interface Props {
  children: React.ReactNode
  delay?: number
}

/** Wraps children and fades them in when scrolled into view. */
export default function ScrollReveal({ children, delay = 0 }: Props): React.JSX.Element {
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const node = ref.current
    if (!node) return
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            node.classList.add('visible')
            io.unobserve(node)
          }
        })
      },
      { threshold: 0.1 },
    )
    io.observe(node)
    return () => io.disconnect()
  }, [])

  return (
    <div ref={ref} className="scroll-reveal" style={{ transitionDelay: `${delay}ms` }}>
      {children}
    </div>
  )
}
